How to build Rudder User Documentation
======================================

== Dependencies

This Document is written using the asciidoc formatting language, and includes
graphviz schemas. To have an output suitable for common use, you need following
software:

=== asciidoc

http://www.methods.co.nz/asciidoc/

Needed to build html and pdf versions.

* On Debian and Ubuntu :

----
apt-get install asciidoc docbook
----

* For other distributions see : http://www.methods.co.nz/asciidoc/INSTALL.html

=== docbook

http://docbook.org/

Needed to build pdf version.

* On Debian and Ubuntu :

----
apt-get install docbook
----

* On Fedora, Centos and RHEL

----
yum install docbook-utils
----

=== graphviz 

http://www.graphviz.org/

Needed to generate graphs.

* On Debian and Ubuntu :

----
apt-get install graphviz
----

== Organisation of files

X_title:: content of the documentation. The list of files to include in the
final document is generated at build from the alphabetically ordered list of
text files contained in these directories.

glossary:: contains glossary entries. At first occurence of a word, the glossary
entry should be included in the text.

images:: contains illustrations.

graphs:: contains graphs generated with graphviz. Graphviz source files are stored
alongside the illustrated text.

themes:: contains material for visual formatting of the output.

== Build

Create HTML and PDF output suitable for distribution.

----
make
make view
----

== Cleanup

Delete all generated files.

----
make clean
----
