@startmindmap education

* 2020
** Impact Tilt - Change Catalyst
* 2019
** Eclipse Foundation Committer
* 2014
** PRINCE2 Foundation
* 2008
** LPIC-1 Linux certified professional
* 1999
** MA in History (“DEA”) - Lumière Lyon 2 University, France
'* 1997
'** BA in French Literature (“Licence”) - Lumière Lyon 2 University, France
@endmindmap
