@startuml education
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
HIDE_STEREOTYPE()
LAYOUT_LANDSCAPE()

Person(user, "Education", "and certifications")
System(2020, "2020")
Container(c2020, "Impact Tilt - Change Catalyst")
System(2019,"2019")
Container(c2019, "Eclipse Foundation Committer")
System(2014,"2014")
Container(c2014, "PRINCE2 Foundation")
System(2008,"2008")
Container(c2008, "Linux certified professional", "LPIC-1")
System(1999,"1999")
Container(c1999,"MA in History", "DEA", "Lumière Lyon 2 University, France")
System(1997,"1997")
Container(c1997,"BA in French Literature", "Licence", "Lumière Lyon 2 University, France")
Rel_Up(2019, 2020, " ")
Rel_Up(2014, 2019, " ")
Rel_Up(2008, 2014, " ")
Rel_Up(1999, 2008, " ")
Rel_Up(1997, 1999, " ")
Rel_R(2020, c2020, " ")
Rel_R(2019, c2019, " ")
Rel_R(2014, c2014, " ")
Rel_R(2008, c2008, " ")
Rel_R(1999, c1999, " ")
Rel_R(1997, c1997, " ")

' :2020;
' note right
' Impact Tilt - Change Catalyst
' end note


' :2019;
' note left
' Eclipse Foundation Committer
' end note

' :2014;
' note right
' PRINCE2 Foundation
' end note

' :2008;
' note left
' LPIC-1 Linux certified professional
' end note

' :1999;
' note right
' MA in History (“DEA”)
' Lumière Lyon 2 University, France
' end note

' :1997;
' note left
' BA in French Literature (“Licence”)
' Lumière Lyon 2 University, France
' end note

@enduml
