@startmindmap experience
'!theme toy
<style>
rootNode {
    MinimumWidth 220
    MaximumWidth 220
}
node {
    MinimumWidth 220
    MaximumWidth 220
}
boxless {
    MaximumWidth 600
}
</style>

*:<b>Red Hat</b>
Software editor
Remote, Brussels, Belgium
Since 2019;
**:<b>Senior Technical Writer</b>
  Since 2019
<b>Technical Writer</b>
  2019-1021;
***_ Lead documentation team\nAuthored content \nDeveloped automation
****_ Podman Desktop
****_ CRC/OpenShift Local
****_ Eclipse Che/OpenShift Dev Spaces
***_ Enablement
****_ Vale linter style guide rules
****_ Antora guidelines

*:<b>Stylelabs</b>
Cloud software editor
Brussels, Belgium
2017-2019;
** <b>Cloud Infrastructure Architect</b>
***_ Lead and developed infrastructure automation: Ansible playbooks for Azure
***_ Researched new technologies (Molecule, Goss, Kubernetes, AWX)

*:<b>Emakina</b>
Digital agency
Brussels, Belgium
2015-2017;
** <b>Senior DevOps</b>
***_ Lead and implemented
****_ Continuous deployment (Jenkins, Artifactory, systemd)
****_ Infrastructure as code (Ansible, Puppet)
****_ Performance assessments (Taurus)
****_ Security assessments (Arachni, Netsparker)

* <b>Antidot</b> \nWeb software editor \nBrussels, Belgium \n2012-2015
** <b>Linux System Administrator</b>
'note right
***_ Managed customer-bound infrastructure projects: Scrum meets Prince2
***_ Lead and implemented
****_ Developer enablement (Gitlab, Jenkins)
****_ Observability (percona-toolkit, Zabbix)
****_ Infrastructure as code (Rudder, Ansible)

* <b>Normation</b> \nSoftware editor \nRemote, Brussels, Belgium \n2011
** <b>Technical Writer</b>
***_ Developed documentation automation (single-sourcing, make)
***_ Authored content (AsciiDoc, Graphviz)
***_ Ran usability tests, reported bugs, and proposed user experience improvements

* <b>Inuits</b> \nOpen Source services \nRemote, Brussels, Belgium \n2010-2011
** <b>Open Source consultant</b>
***_ Managed, analyzed, and implemented technical projects
***_ Presented at technical conferences in Paris, Antwerpen, Leeds
***_ Missions for governement agencies and healthcare organizations

*:<b>Mediaxim</b>
Software editor
Brussels, Belgium
2010
<b>Emakina</b>
Web agency
Brussels, Belgium
2008-2009
<b>FIJ Saint-Gilles</b>
Training center
Brussels, Belgium
2007
<b>Instituts Saint-Luc</b>
Art school
Brussels, Belgium
2006-2007;
** <b>System Administrator</b>
***_ Conceived an IT strategy and translated it into an operational plan
***_ Promoted and lead improvement initiatives
****_ IT deployment automation
****_ IT asset management
****_ Developer tools
****_ Knowledge base
***_ Managed incidents and users requests
***_ Platforms: Linux, macOS, Windows

@endmindmap
