@startmindmap
'!theme toy

* Contributions
**_ Containers committer - Since 2022 - [[https://github.com/orgs/containers/people?query=themr0c]]
**_ Eclipse Foundation Committer - Since 2020 - [[https://accounts.eclipse.org/users/fflorethbault]]
**_ GitHub - Since 2010 - [[https://github.com/themr0c]]
**_ GitLab - Since 2020 - [[https://gitlab.com/ffloreth]]
**_ Rudder - 2012 - documentation [[https://issues.rudder.io/users/13]]

* Community
**_ Presentations - Since 2010 - [[https://themr0c.github.io/]]
**_ Meetups - 2009-2012 - [[http://jeudisdulibre.be/]]
**_ Radio show - 2012-2103 - [[http://www.radiopanik.org/recherche/?q=good+morning+stallman]]

@endmindmap
